export const seedTerms = [
  {
    "id": "term-pwa",
    "termino": "PWA",
    "abreviatura": "PWA",
    "significado_es": "Aplicación Web Progresiva",
    "definicion_corta": "Aplicación web que se comporta como una app instalable de forma nativa.",
    "explicacion": "Una PWA combina lo mejor de las tecnologías web modernas y las aplicaciones nativas. Utiliza Service Workers para almacenamiento en caché, lo que permite funcionamiento offline, notificaciones push, carga ultra rápida e instalación directa en la pantalla de inicio del dispositivo sin pasar por las tiendas de aplicaciones estándar.",
    "tip": "Ideal para proyectos de consulta, catálogos, sistemas administrativos o herramientas de productividad ligeras.",
    "categoria": "Desarrollo de apps",
    "keywords": ["pwa", "offline", "service worker", "cached", "installable", "web app"],
    "relacionados": ["Service Worker", "IndexedDB", "SPA"],
    "favorito": true,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-api",
    "termino": "API",
    "abreviatura": "API",
    "significado_es": "Interfaz de Programación de Aplicaciones",
    "definicion_corta": "Conjunto de reglas y definiciones que permite a diferentes softwares comunicarse entre sí.",
    "explicacion": "Una API actúa como un intermediario o mensajero entre dos sistemas independientes. Permite exponer funciones, datos y servicios de forma controlada y segura para que otros desarrolladores construyan aplicaciones sobre ellos sin necesidad de conocer la implementación interna del sistema original.",
    "tip": "Cuando diseñes APIs, prioriza la documentación detallada utilizando herramientas como Swagger o OpenAPI para que otros desarrolladores la integren en minutos.",
    "categoria": "Programación",
    "keywords": ["api", "rest", "graphql", "http", "endpoints", "integracion"],
    "relacionados": ["Backend", "Frontend", "JSON"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-prompt",
    "termino": "Prompt",
    "abreviatura": "Prompt",
    "significado_es": "Instrucción para Inteligencia Artificial",
    "definicion_corta": "Texto o comando de entrada que se le da a un modelo de lenguaje (como GPT o Claude) para obtener una respuesta.",
    "explicacion": "El prompt es el puente de comunicación directa entre el humano y los modelos generativos. Un prompt bien estructurado no solo pide una tarea, sino que define el rol de la IA, el contexto del problema, las reglas a seguir, ejemplos concretos (few-shot prompting) y el formato exacto en el que se espera la salida.",
    "tip": "Usa la técnica de 'Rol + Contexto + Tarea + Formato' para redactar prompts sumamente específicos y útiles.",
    "categoria": "IA",
    "keywords": ["prompt", "generative ai", "llm", "instructions", "copilot", "chatgpt"],
    "relacionados": ["RAG", "Embedding", "IA"],
    "favorito": true,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-ux",
    "termino": "UX",
    "abreviatura": "UX",
    "significado_es": "Experiencia de Usuario",
    "definicion_corta": "Proceso de diseñar productos digitales que ofrecen experiencias relevantes y significativas a los usuarios.",
    "explicacion": "La Experiencia de Usuario (UX) abarca todos los aspectos de la interacción del usuario final con la empresa, sus servicios y sus productos. Se enfoca en entender profundamente las necesidades de los usuarios, sus capacidades y limitaciones, así como en diseñar flujos lógicos, arquitectura de información clara y navegación intuitiva.",
    "tip": "Realiza pruebas de usabilidad tempranas con usuarios reales (incluso con prototipos de papel) para detectar fricciones antes de escribir una sola línea de código.",
    "categoria": "UX/UI",
    "keywords": ["ux", "user experience", "research", "wireframe", "usability", "interaction"],
    "relacionados": ["UI", "Responsive", "Design System"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-ui",
    "termino": "UI",
    "abreviatura": "UI",
    "significado_es": "Interfaz de Usuario",
    "definicion_corta": "Aspecto visual y los elementos interactivos que permiten a las personas comunicarse con una aplicación.",
    "explicacion": "La UI (User Interface) se concentra en los elementos visuales del producto digital: la tipografía, los colores, los botones, las imágenes, las animaciones y otros puntos de contacto visuales. Su objetivo es hacer que la interfaz sea visualmente atractiva, estéticamente coherente y fácil de escanear y usar para el usuario.",
    "tip": "Mantén la coherencia visual construyendo un Sistema de Diseño con tokens para colores, espacios y tipografía en lugar de inventar valores ad-hoc sobre la marcha.",
    "categoria": "UX/UI",
    "keywords": ["ui", "interface", "design", "colors", "typography", "components", "visuals"],
    "relacionados": ["UX", "Responsive", "Branding"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-responsive",
    "termino": "Responsive Design",
    "abreviatura": "Responsive",
    "significado_es": "Diseño Web Adaptativo",
    "definicion_corta": "Práctica de diseño web que hace que las páginas se visualicen correctamente en todos los dispositivos y tamaños de pantalla.",
    "explicacion": "El diseño responsivo utiliza rejillas fluidas, imágenes flexibles y media queries en CSS para adaptar de forma dinámica el diseño de la aplicación. Se asegura de que la experiencia sea igual de óptima en un teléfono inteligente pequeño, una tablet o un monitor de escritorio ultra-ancho.",
    "tip": "Adopta el enfoque 'Mobile-First': escribe tus estilos base para pantallas móviles primero y luego añade media queries con min-width para pantallas más grandes.",
    "categoria": "Diseño web",
    "keywords": ["responsive", "media queries", "mobile-first", "flexbox", "css grid", "layout"],
    "relacionados": ["UI", "UX", "SPA"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-frontend",
    "termino": "Frontend",
    "abreviatura": "Frontend",
    "significado_es": "Desarrollo del Lado del Cliente",
    "definicion_corta": "Parte de un sitio web o aplicación con la que los usuarios interactúan de forma directa.",
    "explicacion": "El desarrollo Frontend abarca todo lo que se ejecuta en el navegador web del usuario. Se construye principalmente con HTML para la estructura, CSS para el diseño visual y las transiciones, y JavaScript para la interactividad y la conexión con servicios backend.",
    "tip": "Optimiza el rendimiento reduciendo el tamaño de tus scripts, difiriendo la carga de JS no crítico y minimizando el uso de dependencias externas redundantes.",
    "categoria": "Programación",
    "keywords": ["frontend", "javascript", "html", "css", "browser", "dom", "ui"],
    "relacionados": ["Backend", "API", "SPA"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-backend",
    "termino": "Backend",
    "abreviatura": "Backend",
    "significado_es": "Desarrollo del Lado del Servidor",
    "definicion_corta": "Parte lógica del servidor, bases de datos y la arquitectura técnica que hace funcionar una aplicación tras bambalinas.",
    "explicacion": "El Backend se encarga del procesamiento de datos, las reglas de negocio, la seguridad de las transacciones, la autenticación de usuarios y la persistencia en bases de datos. Los usuarios no lo ven directamente, sino que interactúan con él a través de las APIs solicitadas por el Frontend.",
    "tip": "Implementa validaciones estrictas de datos en el Backend, incluso si el Frontend ya las realiza, para prevenir ataques de inyección y corrupción de datos.",
    "categoria": "Programación",
    "keywords": ["backend", "database", "server", "nodejs", "security", "node", "crud"],
    "relacionados": ["Frontend", "API", "IndexedDB"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-spa",
    "termino": "SPA",
    "abreviatura": "SPA",
    "significado_es": "Aplicación de una Sola Página",
    "definicion_corta": "Aplicación web que carga una única página HTML y actualiza dinámicamente el contenido a medida que el usuario interactúa.",
    "explicacion": "Las Single Page Applications (SPA) evitan la recarga completa del navegador al navegar por diferentes secciones. La aplicación intercepta las solicitudes de enlace y renderiza dinámicamente los nuevos elementos en la vista usando JavaScript, lo que resulta en transiciones extremadamente rápidas y fluidas similares a las de una app de escritorio nativa.",
    "tip": "Asegúrate de manejar adecuadamente el historial de navegación del navegador (History API) para que los botones 'atrás' y 'adelante' sigan funcionando correctamente.",
    "categoria": "Diseño web",
    "keywords": ["spa", "single page", "routing", "dynamic", "javascript", "history api"],
    "relacionados": ["PWA", "Frontend", "UX"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-indexeddb",
    "termino": "IndexedDB",
    "abreviatura": "IndexedDB",
    "significado_es": "Base de Datos Indexada del Navegador",
    "definicion_corta": "API de almacenamiento local estructurado y transaccional integrada de forma nativa en los navegadores web.",
    "explicacion": "IndexedDB es una base de datos no relacional de tipo clave-valor orientada a objetos que permite guardar grandes volúmenes de datos del lado del cliente, incluyendo archivos o blobs. Ofrece transacciones, índices para búsquedas de alto rendimiento y funciona de forma asíncrona para evitar bloquear el hilo principal de renderizado de la aplicación.",
    "tip": "Es perfecta para aplicaciones Offline-First que necesitan almacenar datos complejos sin la latencia de una conexión a internet.",
    "categoria": "Programación",
    "keywords": ["indexeddb", "database", "storage", "offline-first", "browser db", "transactions"],
    "relacionados": ["PWA", "Service Worker", "Backend"],
    "favorito": true,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-serviceworker",
    "termino": "Service Worker",
    "abreviatura": "Service Worker",
    "significado_es": "Script en Segundo Plano del Navegador",
    "definicion_corta": "Script que el navegador ejecuta en segundo plano, separado de la página web, habilitando funciones offline.",
    "explicacion": "Un Service Worker actúa como un proxy de red del lado del cliente. Intercepta de manera transparente las peticiones HTTP que hace la aplicación web, permitiendo decidir si se recupera un recurso directamente desde la red o desde una caché de archivos locales previamente guardada. Esto hace posible la experiencia 100% offline y la carga instantánea.",
    "tip": "Ten cuidado con el ciclo de vida y la actualización del Service Worker. Asegúrate de forzar la activación cuando haya código nuevo para que los usuarios vean las actualizaciones inmediatamente.",
    "categoria": "Desarrollo de apps",
    "keywords": ["service worker", "worker", "cache", "offline", "proxy", "network", "pwa"],
    "relacionados": ["PWA", "IndexedDB", "Responsive"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-seo",
    "termino": "SEO",
    "abreviatura": "SEO",
    "significado_es": "Optimización para Motores de Búsqueda",
    "definicion_corta": "Práctica de optimizar un sitio web para que aparezca orgánicamente en posiciones destacadas de buscadores como Google.",
    "explicacion": "El SEO (Search Engine Optimization) engloba tácticas técnicas y de contenido. Incluye la optimización de velocidad de carga, estructuración de metadatos, diseño móvil responsivo, investigación y colocación estratégica de palabras clave y la jerarquía de etiquetas semánticas HTML para facilitar la indexación por parte de los robots de búsqueda.",
    "tip": "Usa una estructura clara con un único H1 por página y escribe textos que aporten valor real a los humanos en lugar de sobrecargar la página con palabras clave sin sentido.",
    "categoria": "Marketing digital",
    "keywords": ["seo", "marketing", "google", "keywords", "ranking", "indexing", "semantic html"],
    "relacionados": ["CTR", "Conversión", "Landing Page"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-ctr",
    "termino": "CTR",
    "abreviatura": "CTR",
    "significado_es": "Tasa de Clics en Relación a Impresiones",
    "definicion_corta": "Porcentaje de personas que hacen clic en un enlace en comparación al total que vieron dicho enlace.",
    "explicacion": "El CTR (Click-Through Rate) es una métrica clave en publicidad digital y SEO. Mide la relevancia y efectividad de un anuncio, un fragmento de búsqueda en Google o un llamado a la acción. Un CTR alto suele indicar que la oferta o el título propuesto resuena fuertemente con la intención de búsqueda de la audiencia.",
    "tip": "Mejora el CTR de tus resultados de búsqueda escribiendo etiquetas Meta Description persuasivas y añadiendo emojis sutiles que llamen la atención sin perder el tono profesional.",
    "categoria": "Marketing digital",
    "keywords": ["ctr", "clicks", "impressions", "metrics", "marketing", "ads"],
    "relacionados": ["SEO", "Conversión", "Landing Page"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-conversion",
    "termino": "Conversión",
    "abreviatura": "Conversión",
    "significado_es": "Acción Clave Lograda de un Usuario",
    "definicion_corta": "Ocurre cuando un visitante de un sitio web realiza una acción deseada previamente definida como meta.",
    "explicacion": "Una conversión representa el éxito final de un flujo de usuario. Puede consistir en realizar una compra en una tienda online, completar un formulario de contacto, suscribirse a un boletín por correo, descargar un archivo o instalar una aplicación PWA. La tasa de conversión mide la efectividad general de la interfaz y la propuesta de valor.",
    "tip": "Reduce los campos de tus formularios al mínimo estrictamente necesario. Cada campo adicional reduce drásticamente tu tasa de conversión.",
    "categoria": "Marketing digital",
    "keywords": ["conversion", "conversion rate", "cro", "leads", "sales", "analytics"],
    "relacionados": ["SEO", "CTR", "Landing Page"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-branding",
    "termino": "Branding",
    "abreviatura": "Branding",
    "significado_es": "Gestión Estratégica de Marca",
    "definicion_corta": "Proceso de construcción y mantenimiento de la identidad, personalidad y percepción de una marca en el mercado.",
    "explicacion": "El branding va mucho más allá de un logotipo bonito. Abarca los valores fundamentales de la organización, la promesa de la marca, su tono de voz corporativo, la tipografía corporativa y las emociones que genera en los clientes. Busca diferenciar un producto digital o empresa de sus competidores y crear una conexión de lealtad duradera.",
    "tip": "El mejor branding digital es coherente. Asegúrate de usar la misma paleta de colores, tipografías y tono de voz tanto en tu sitio web como en tus redes sociales y boletines de correo.",
    "categoria": "Branding",
    "keywords": ["branding", "marca", "logo", "identity", "assets", "voice", "design system"],
    "relacionados": ["UI", "UX", "Landing Page"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-landingpage",
    "termino": "Landing Page",
    "abreviatura": "Landing Page",
    "significado_es": "Página de Destino",
    "definicion_corta": "Página web independiente diseñada específicamente con el único propósito de convertir visitantes en prospectos.",
    "explicacion": "Una página de destino (Landing Page) se diseña con un enfoque único e ininterrumpido. A diferencia de un sitio corporativo general, no tiene enlaces de navegación normales que puedan distraer al usuario. Todo el diseño, el copy, los testimonios y los botones de llamado a la acción (CTA) se dirigen exclusivamente a lograr que el visitante complete una única conversión.",
    "tip": "Mantén tu propuesta de valor principal visible por encima del primer pliegue de la pantalla (above the fold) para enganchar al usuario en menos de 3 segundos.",
    "categoria": "Marketing digital",
    "keywords": ["landing", "page", "conversion", "lead magnet", "cta", "copywriting"],
    "relacionados": ["SEO", "CTR", "Conversión"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-embedding",
    "termino": "Embedding",
    "abreviatura": "Embedding",
    "significado_es": "Representación Vectorial de Datos",
    "definicion_corta": "Representación numérica de palabras, frases o documentos en un espacio vectorial de alta dimensión que captura su significado semántico.",
    "explicacion": "Los embeddings transforman textos complejos en arrays o listas de números decimales de tamaño fijo (ej. 1536 dimensiones). La magia de los embeddings es que los conceptos que tienen significados semánticos similares o relacionados terminan localizándose muy cerca unos de otros dentro del espacio matemático vectorial, facilitando búsquedas por concepto en lugar de por coincidencia de palabras exactas.",
    "tip": "Utiliza embeddings para implementar buscadores semánticos en tu aplicación. Podrán entender que 'crear una app' y 'codificar un software' expresan intenciones de búsqueda idénticas.",
    "categoria": "IA",
    "keywords": ["embedding", "vector", "llm", "semantic search", "artificial intelligence", "database"],
    "relacionados": ["RAG", "Prompt", "IA"],
    "favorito": false,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  },
  {
    "id": "term-rag",
    "termino": "RAG",
    "abreviatura": "RAG",
    "significado_es": "Generación Aumentada por Recuperación",
    "definicion_corta": "Técnica que mejora las respuestas de un modelo de lenguaje (LLM) al proporcionarle datos externos confiables como contexto.",
    "explicacion": "La Generación Aumentada por Recuperación (RAG) resuelve el problema de las alucinaciones y la falta de datos actualizados en los LLMs. Cuando un usuario hace una pregunta, el sistema busca primero documentos o datos relevantes en una base de datos propia (ej. mediante embeddings en una base vectorial). Luego, inserta esos documentos recuperados junto al prompt original y le pide al LLM que responda basándose estrictamente en esa información.",
    "tip": "Es el estándar de oro actual para crear chatbots corporativos o asistentes virtuales inteligentes que responden basados exclusivamente en la documentación o manuales de la empresa.",
    "categoria": "IA",
    "keywords": ["rag", "retrieval", "llm", "context", "embeddings", "vector search"],
    "relacionados": ["Prompt", "Embedding", "IA"],
    "favorito": true,
    "fecha_creacion": "2026-05-18",
    "fecha_actualizacion": "2026-05-18",
    "veces_consultado": 0,
    "origen": "semilla",
    "estado": "activo"
  }
];
